platform :ios, '15.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'BrailleEbookFront' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath]
  )

  post_install do |installer|
    react_native_post_install(installer)

    # ✅ 모든 Pod 타겟의 Deployment Target 강제
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |bc|
        bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
